language: python
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    install: pip install tox codecov
    python: 3.6
    env:
    - TOXENV=py36
    script: tox
  - stage: deploy
    script: skip
    python: 3.6
    deploy:
      provider: pypi
      username: bgolden
      password:
        secure: SD+bos8dSOzVTCy8QHNcUaE+Jtrys7MAX/7EvqoFZATUcs96M2mtzJ2pP1cn9AdQAqJSFC5hFCezuKw7qWUXHs4HlqoxD6mNfjP5jhc5KaTs2Det7ukfkJheVzzY9l6EhnKpmnKOZikXhahFLTs7hvQgLG6/PPcilmJrCh5xQeLOBvbBTzlhhfjrvruSd8PScgCitzqnzJjiHuVfiicX/ACqP6QSrEh3V5XV+hC/WTrU2gwmJJU2z3ZIlorbvxEWKIjTgwQrZc/Sz8P9U1UoW7qOOEcbzFyQQppEMdJsI/eElmYbBTPP8jQzCWyNYZ0hz/I378bDmK72c9nXLFJa1A2zChNqkhdTfIUS1H791DWXSmjKtcn3c9QNOV0biaDDXlQrsV5I9YtNnoU/DuJLy/5gdIEEdk0HfF8sKmEB28r2xVx8MZTf3UgtTyarapaXQ5PgVvTCLsEXMv+jx49ftquTtAR/SYU4j8rohm2xtkowElOImz92hRXgq1u2rBepFmTdEXvpTwW+RXJhXXKMs/s3Tq17Ngepc/7ZeT556IHNZyEB7pbmQdBJWVte+Su+xLf9tYSGm+I/lCn6koyOKlHeeSkvbhABTJ2WWmdrdBhFwFWxuFqojlOmk/WmRGp5tFMMI6tL5mgrSyaZ7zww41/sx9xUPSLjCcINMzs6rhE=
      distributions: sdist bdist_wheel
      on:
        tags: true
after_success:
- codecov --env TRAVIS_OS_NAME,TOXENV
